### ISSUE TITLE
BUG of wifi config

### ISSUE THREAD

**Issue by qingchuwudi** [EspressifApp/IOT-Espressif-Android#1]
Hi,

> 我们在使用该app二次封装时遇到一个BUG，花费了较长时间定才位到它。

问题描述：**IOT-Espressif-Android （包括最新ESP8266固件）在配置、保存、使用WiFi密码时没有对特殊字符检测、处理。**

二次封装后的app在某些机型（例子见下面）上输入的WiFi密码，传输到 IOT-Espressif-Android 后会多出一个换行符（这种特殊字符不是不能作为WiFi密码使用吗？），而 IOT-Espressif-Android 和 ESP8266 没有做任何处理便保存使用。这让我们在使用某些特定机型测试一键配置时总是失败（大多数机型上没问题）。

### 手机信息：

|型号|Android版本|内核版本|版本号|
|:--|:--|:--|:--|
|ZTE N9180|4.4.2|3.4.0-g1520d93-00060-gf327851nubia@swlab-1t042 #1 Fri Aug 1 19:43:04 CST 2014| ZTE N9180_CNTelecom_V1.05|

PS: 我们现在做了特殊字符处理，希望官方给出的 app 和 固件 也都能处理此类问题。

**Comment by EspressifApp** [comment]
非常感谢你们能及时告知。

1. wifi的相关规范中，并未限制密码必须为可见字符; 
2. Android中EditText设置android:inputType=“textPassword”后，就无法输入回车符。

我们提供的API，需要外部在调用时，给出正确的密码字符。所以，外部调用或二次开发的库，有保证密码正确性及完整性的义务。
